name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Compile
      run: javac -d out *.java

    - name: Run tests
      run: java -cp out org.junit.runner.JUnitCore NumberProcessorTests







