name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install SDKMAN
      run: curl -s "https://get.sdkman.io" | bash

    - name: Load SDKMAN
      run: source "$HOME/.sdkman/bin/sdkman-init.sh"

    - name: Install Gradle
      run: sdk install gradle 7.2

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test


